let musicDB = [
    {
        id: 0,
        name: "I love you baby",
        author_name: "Frank Sinatra",
        img: "sinatra.jfif",
        lang: "ENGLISH",
        timesPlayed: 0,
        musicName: "frank-sinatra-i-love-you-baby(mp3gid.me).mp3",
    },
    {
        id: 1,
        name: "My way",
        author_name: "Frank Sinatra",
        img: "myway.jfif",
        lang: "ENGLISH",
        timesPlayed: 0,
        musicName: "frank-sinatra-my-way-remastered-album-version-the-frank-sinatra-collection(mp3gid.me).mp3",
    },
    {
        id: 2,
        name: "Just the two of us",
        author_name: "Grover Washington Jr. Feat. Bill Withers",
        img: "justtwo.jpg",
        lang: "ENGLISH",
        timesPlayed: 0,
        musicName: "grover-washington-jr-feat-bill-withers-just-the-two-of-us(mp3gid.me).mp3",
    },
    {
        id: 3,
        name: "Cheri Cheri Lady",
        author_name: "Modern Talking",
        img: "artworks-qZ1KWUIeNp3yzVtF-iSwgXQ-t500x500.jpg",
        lang: "ENGLISH",
        timesPlayed: 0,
        musicName: "vechnye-hity-modern-talking-cheri-cheri-lady(mp3gid.me).mp3",
    },
    {
        id: 4,
        name: "Дождь",
        author_name: "Батырхан Шукенов",
        img: "Дождь.jfif",
        lang: "RUSSIAN",
        timesPlayed: 0,
        musicName: "Батыр Шукенов - Дождь.mp3",
    },
    {
        id: 5,
        name: "Taspa",
        author_name: "Dosekesh",
        img: "taspa.jpg",
        lang: "KAZAKH",
        timesPlayed: 0,
        musicName: "Dosekesh - Taspa.mp3",
    },
    {
        id: 6,
        name: "Riptide",
        author_name: "Vance Joy",
        img: "riptide.jfif",
        lang: "ENGLISH",
        timesPlayed: 0,
        musicName: "Vance_Joy_-_Riptide_(musmore.com).mp3",
    },
    {
        id: 7,
        name: "Adventure of a Lifetime",
        author_name: "ColdPlay",
        img: "Adventure_of_a_Lifetime_(song).jpg",
        lang: "ENGLISH",
        timesPlayed: 0,
        musicName: "coldplay-adventure-of-a-lifetime-adventure-of-a-lifetime(mp3gid.me).mp3",
    },
    {
        id: 8,
        name: "До скорой встречи",
        author_name: "Звери",
        img: "zveri.jfif",
        lang: "RUSSIAN",
        timesPlayed: 0,
        musicName: "zveri-zveri-do-skoroj-vstrechi(mp3gid.me).mp3",
    },
    {
        id: 9,
        name: "Oinamaqo",
        author_name: "Ninety one",
        img: "ninety-one-oinamaqo.png",
        lang: "KAZAKH",
        timesPlayed: 0,
        musicName: "ninety-one-oinamaqo-ojnamao_(muzzona.kz).mp3",
    },
    {
        id: 10,
        name: "Uide",
        author_name: "Darkhan Juzz",
        img: "juzz.jpg",
        lang: "KAZAKH",
        timesPlayed: 0,
        musicName: "Darkhan juzz - ҮЙДЕ 2019_muztok.com.mp3",
    },
    {
        id: 11,
        name: "Режиссер",
        author_name: "Градусы",
        img: "rezhisser.jpg",
        lang: "RUSSIAN",
        timesPlayed: 0,
        musicName: "hity-2010-gradusy-rezhisser(mp3gid.me).mp3",
    },
    {
        id: 12,
        name: "Белые Розы",
        author_name: "Юрий Шатунов",
        img: "yurij-shatunov-belye-rozy.jpeg",
        lang: "RUSSIAN",
        timesPlayed: 0,
        musicName: "jurij-shatunov-belye-rozy-akm-remix-2022(mp3gid.me).mp3",
    },
    {
        id: 13,
        name: "Белые Розы",
        author_name: "Юрий Шатунов",
        img: "Noch.jfif",
        lang: "RUSSIAN",
        timesPlayed: 0,
        musicName: "8-super-diskoteka-90-h-jurij-shatunov-sedaja-noch(mp3gid.me).mp3",
    },
];

export default musicDB;
